name: Build and Test

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        tfm: [ net6, net8 ]
        include:
          - tfm: net6
            dotnet-version: 6.0.x 
          - tfm: net8
            dotnet-version: 8.0.x 

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Display dotnet version
        run: dotnet --version
      - name: Build
        run: dotnet build --configuration Release --framework ${{ matrix.tfm }} ./src/QLimitive/QLimitive.csproj
      - name: Test
        run: dotnet test --verbosity normal --configuration Release --framework ${{ matrix.tfm }} ./src/UnitTests/UnitTests.csproj