name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        target-framework: [ 'net6.0' ]

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - name: Display dotnet version
        run: dotnet --version
      - name: Build
        run: dotnet build --configuration Release --framework ${{ matrix.target-framework }} ./src/QLimitive/QLimitive.csproj
      - name: Test
        run: dotnet test --verbosity normal --configuration Release --framework ${{ matrix.target-framework }} ./src/UnitTests/UnitTests.csproj